name: Deploy static website to Azure Web App

on:
  push:
    branches:
      - main  # o cambia por tu rama principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Upload static files to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: WebServiceAppKG  # <-- cámbialo
        slot-name: 'production'
        package: ./main                      # <-- carpeta donde está index.html
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
